# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HermitFinal' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'SwiftyJSON'
pod 'Parse'
pod 'Firebase'
  # Pods for HermitFinal

  target 'HermitFinalTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
