# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'fiesp5th' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'AccountKit'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  # Pods for fiesp5th

end
