# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!

def shared_pods
    pod 'Alamofire'
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
    pod 'SwiftyJSON'
end

target 'PiggyBank' do
    shared_pods
end

target 'PiggyBank-SMS' do
    shared_pods
    pod 'JSQMessagesViewController'
end
