# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Piggy' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  # Pods for Piggy
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'GhostTypewriter'
  pod 'KeychainSwift'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  pod "Hero"
end
