# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HackthonGlobo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
project 'HackthonGlobo'
		
  # Pods for HackthonGlobo
	pod 'Alamofire'
	pod 'AlamofireObjectMapper', '~> 4.0'
	pod 'Regift'
    pod 'FacebookCore'
    pod 'FacebookLogin'
    pod 'FacebookShare'
    pod 'SFFocusViewLayout', '~> 3.0'
end
