# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Saiga' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'alamofire5'
pod 'lottie-ios'
pod 'DTMHeatmap'
pod 'TagListView'
end
