# Uncomment the next line to define a global platform for your project
target 'Torq' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Torq
  pod 'Cosmos', '~> 17.0'
  pod 'SoundWave'
  pod 'ScrollableGraphView'
  pod 'Charts'
  pod 'Koloda'
  pod 'Alamofire'
  pod 'AlamofireImage'
  pod 'lottie-ios'
end
