# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'SHIFT' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SHIFT
pod 'FBSDKShareKit'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'AccountKit'
pod 'SwiftQRCode'
pod 'SwiftyJSON'
pod 'AlamofireImage'
end
